### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by blimjoe** [waveshare/2-CH-RS485-HAT#1]
已经改了config文件，安装了库。测试example时出现了问题。
/dev/下的ttySC0和ttySC1两个设备在没有插上HAT时也是有的，是insmod了某个module就会出现吗？怎么查看这两个设备在工作呢？
```  
pi@raspberrypi:~/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/examples $ sudo python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import serial
  File "/usr/local/lib/python2.7/dist-packages/serial/__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "/usr/local/lib/python2.7/dist-packages/serial/utilities/__init__.py", line 5, in <module>
    compatibility.backport()  # noqa
  File "/usr/local/lib/python2.7/dist-packages/serial/utilities/compatibility.py", line 28, in backport
    exec(BACKWARDS_COMPATIBILITY_IMPORTS, frame.f_globals, frame.f_locals)
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/future/standard_library/__init__.py", line 485, in install_aliases
    import test
  File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/examples/test.py", line 16, in <module>
    from waveshare_2_CH_RS485_HAT import RS485
  File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/RS485.py", line 10, in <module>
    import SC16IS752
  File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/SC16IS752.py", line 79, in <module>
    com = config.config()
  File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/config.py", line 24, in __init__
    self._spi = SPI.SpiDev(0, 0)
IOError: [Errno 2] No such file or directory
```

**Comment by waveshare** [comment]
这个只要是加入语句就会生成设备




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "waveshare/2-CH-RS485-HAT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月29日(星期二) 下午2:05
收件人:&nbsp;"waveshare/2-CH-RS485-HAT"<2-CH-RS485-HAT@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[waveshare/2-CH-RS485-HAT] 测试失败 (#1)





 
已经改了config文件，安装了库。测试example时出现了问题。
 /dev/下的ttySC0和ttySC1两个设备在没有插上HAT时也是有的，是insmod了某个module就会出现吗？怎么查看这两个设备在工作呢？
 pi@raspberrypi:~/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/examples $ sudo python main.py Traceback (most recent call last):   File "main.py", line 3, in <module&gt;     import serial   File "/usr/local/lib/python2.7/dist-packages/serial/__init__.py", line 10, in <module&gt;     from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request   File "/usr/local/lib/python2.7/dist-packages/serial/utilities/__init__.py", line 5, in <module&gt;     compatibility.backport()  # noqa   File "/usr/local/lib/python2.7/dist-packages/serial/utilities/compatibility.py", line 28, in backport     exec(BACKWARDS_COMPATIBILITY_IMPORTS, frame.f_globals, frame.f_locals)   File "<string&gt;", line 5, in <module&gt;   File "/usr/local/lib/python2.7/dist-packages/future/standard_library/__init__.py", line 485, in install_aliases     import test   File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/examples/test.py", line 16, in <module&gt;     from waveshare_2_CH_RS485_HAT import RS485   File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/RS485.py", line 10, in <module&gt;     import SC16IS752   File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/SC16IS752.py", line 79, in <module&gt;     com = config.config()   File "/home/pi/testcode/2-CH-RS485-HAT/RaspberryPi/user_dev/python/lib/waveshare_2_CH_RS485_HAT/config.py", line 24, in __init__     self._spi = SPI.SpiDev(0, 0) IOError: [Errno 2] No such file or directory

**Comment by blimjoe** [comment]
请问这个问题该如何排查呢？
